### ISSUE TITLE
fmod.dll and fmodstudio.dll not found after successful build!

### ISSUE THREAD

**Issue by MohitSethi99** [danhuynh0803/Campfire#90]

**Comment by danhuynh0803** [comment]
Thanks for notifying us of this issue. This is something related to our cmake scripts, which should move the fmod dlls to the appropriate build directory. We'll look into it. If you're interested in using a workaround, you can copy the fmod.dll and fmodstudio.dll into the build directory of the editor, which should at least get the editor to run

**Comment by MohitSethi99** [comment]
Thanks. Workaround works :P

**Comment by MohitSethi99** [comment]
Re-opened because bug is not yet resolved.
